usethis::use_package('magrittr')
usethis::use_package('stats')
usethis::use_package('questionr')
usethis::use_package('ggplot2')
usethis::use_package('ggpubr')
usethis::use_package('dplyr')
usethis::use_build_ignore("devtools_history.R")
