usethis::use_package('magrittr')
usethis::use_package('stats')
usethis::use_package('questionr')
usethis::use_package('ggplot2')
usethis::use_package('ggpubr')
usethis::use_package('dplyr')
usethis::use_package('readxl')
usethis::use_package('ggradar')
usethis::use_package('scales')
usethis::use_package('tibble')
usethis::use_build_ignore("devtools_history.R")
devtools::document()

fromage=read.table("D:/Documents/M2 SISE/Programmation R/Projet/antoine/data_multi.txt",header=T,row.names = 1,sep = "\t",dec=".")

df_test<-read_xlsx("D:/Documents/M2 SISE/Programmation R/Projet/OneDrive_1_07-12-2020/df_test.xlsx")
pred_reel_3c <- read_xlsx("C:/Users/alexi/Desktop/ProjetR/Données/test.xlsx")
pred_reel_2c<-read_xlsx("C:/Users/alexi/Desktop/ProjetR/Données/test3.xlsx")
pred_reel_2c_bis<-read_xlsx("C:/Users/alexi/Desktop/ProjetR/Données/test4.xlsx")

setwd("C:/Users/alexi/Desktop/ProjetR/Données/")
usethis::use_data(df_test, overwrite=TRUE)
usethis::use_data(pred_reel_3c)
usethis::use_data(pred_reel_2c)
usethis::use_data(pred_reel_2c_bis)
